[project]
name = "2gis-qa-task"
version = "1.0.0"
description = "Test task for 2gis QA candidates"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    # fixtures replacement tool, it aims to replace static,
    # hard to maintain fixtures with easy-to-use factories for complex objects.
    "factory-boy>=3.3.3",
    # fully featured HTTP client for Python 3
    "httpx>=0.28.1",
    # Implements request retry for HTTPX
    "httpx-retries>=0.4.2",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.1.0",
    # Pytest plugin making the output look better
    "pytest-sugar>=1.1.1",
    # Pytest plugin allowing you to run tests in multiprocessing
    "pytest-xdist>=3.8.0",
    # Pragmatic, general‑purpose testing framework for Python
    "vedro>=1.15.0",
    # vedro‑httpx is an official plugin for the Vedro testing framework that wraps HTTPX
    "vedro-httpx>=0.8.1",
]
[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "-n=auto",
    "--asyncio-mode=auto"
]
